### ISSUE TITLE
Helm Exporter waiting to connect?

### ISSUE THREAD

**Issue by darren-bell-nanthealth** [sstarcher/helm-exporter#15] opened 2019-06-03 09:37 UTC
Hi
Ive tried to deploy the exporter on a kubernetes cluster. Ive deployed it in the kube-system namespace where tiller exists. The tiller service is: tiller-deploy.kube-system:44134 TCP

**Comment by sstarcher** [comment] 2019-06-04 18:38
duplicate of #16

**Closed by sstarcher** 2019-06-04 18:38 UTC
